[profile.default]
libs            = ["lib"]                  # A list of library directories
optimizer       = false                    # Enable or disable the solc optimizer
optimizer_runs  = 200                      # The number of optimizer runs
verbosity       = 3                        # The verbosity of tests
fs_permissions = [{ access = "read-write", path = "./"}]
